# .gitlab-ci.yml
image: cypress/included:13.6.6

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

api_tests:
  stage: test
  script:
    - npx cypress run --spec "cypress/e2e/api-tests/productsApiTest.cy.js"
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week

ui_tests:
  stage: test
  script:
    - npx cypress run --spec "cypress/e2e/ui-tests/productsUiTest.cy.js"
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week