# .gitlab-ci.yml
image: cypress/included:14.4.0

stages:
  - test

before_script:
  - npm ci

api_tests:
  stage: test
  script:
    - npx cypress run --browser electron --spec "cypress/e2e/api-tests/**/*.cy.js"

ui_tests:
  stage: test
  script:
    - npx cypress run --browser electron --spec "cypress/e2e/ui-tests/**/*.cy.js"